Repository sparta/sparta, pull requests merged in 2019-04, with the labels that each got.

#34 Add min, max, and variance to timing breakdown, similar to LAMMPS
  src/finish.cpp
Labels: enhancement

#48 Add low memory version of writing and reading restart files
  doc/global.txt
  src/KOKKOS/particle_kokkos.cpp
  src/comm.cpp
  src/grid.cpp
  src/grid.h
  src/particle.cpp
  src/particle.h
  src/read_restart.cpp
  src/write_restart.cpp
  src/write_restart.h
Labels: enhancement

#50 Fix bug in collision scattering velocities
  src/KOKKOS/collide_vss_kokkos.cpp
  src/collide_vss.cpp
Labels: bugfix

#59 Velocity sign bugfix
  src/KOKKOS/collide_vss_kokkos.cpp
  src/collide_vss.cpp
Labels: bugfix

#60 Update react_tce_kokkos to match non-Kokkos version
  src/KOKKOS/react_tce_kokkos.h
Labels: KOKKOS package, bugfix

#61 Fix broken virtual function in compute_surf_kokkos
  src/KOKKOS/compute_surf_kokkos.cpp
  src/KOKKOS/compute_surf_kokkos.h
Labels: KOKKOS package, bugfix

#62 delete a redundant line
  src/grid.cpp
Labels: enhancement
