Repository sparta/sparta, pull requests merged in 2019-01, with the labels that each got.

#24 Fix overflow issue with large grids
  src/create_grid.cpp
  src/grid_id.cpp
Labels: bugfix

#30 Surf2grid
  doc/global.txt
  src/comm.cpp
  src/comm.h
  src/cut2d.cpp
  src/cut2d.h
  src/cut3d.cpp
  src/cut3d.h
  src/fix_move_surf.cpp
  src/grid.cpp
  src/grid.h
  src/grid_id.cpp
  src/grid_surf.cpp
  src/hash_options.h
  src/hashlittle.cpp
  src/hashlittle.h
  src/move_surf.h
  src/my_page.h
  src/read_surf.cpp
  src/surf.h
  src/update.cpp
Labels: enhancement

#27 Fix issue in compute_tvib_grid
  src/compute_tvib_grid.cpp
Labels: bugfix

#32 Fix hang when divide by 0 in variable formula
  src/variable.cpp
Labels: bugfix

#35 Add duplicated memory option to KOKKOS package
  doc/accelerate_kokkos.txt
  src/KOKKOS/compute_grid_kokkos.cpp
  src/KOKKOS/compute_grid_kokkos.h
  src/KOKKOS/compute_thermal_grid_kokkos.cpp
  src/KOKKOS/compute_thermal_grid_kokkos.h
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/kokkos_type.h
Labels: KOKKOS package, enhancement

#36 Use 1D views to allocate scalars in KOKKOS package
  src/KOKKOS/collide_vss_kokkos.cpp
  src/KOKKOS/collide_vss_kokkos.h
  src/KOKKOS/update_kokkos.cpp
  src/KOKKOS/update_kokkos.h
Labels: KOKKOS package, enhancement
