Repository sparta/sparta, pull requests merged in 2020-05, with the labels that each got.

#140 Fix segfault issue in read_surf
  src/read_surf.cpp
Labels: bugfix

#134 Allow read/write of restart files larger than 2 GB
  src/particle.cpp
  src/particle.h
  src/pointers.h
  src/read_restart.cpp
  src/read_restart.h
  src/write_restart.cpp
  src/write_restart.h
Labels: enhancement

#145 cleaned up new code comments
  src/collide_vss.cpp
Labels: documentation

#146 Fix compile warnings in Kokkos surf_collide styles
  src/KOKKOS/surf_collide_diffuse_kokkos.h
  src/KOKKOS/surf_collide_piston_kokkos.h
  src/KOKKOS/surf_collide_specular_kokkos.h
  src/KOKKOS/surf_collide_transparent_kokkos.h
  src/KOKKOS/surf_collide_vanish_kokkos.h
Labels: KOKKOS package, enhancement

#157 Add Makefile for Summit machine
  src/MAKE/Makefile.summit_kokkos
Labels: KOKKOS package, enhancement

#147 Fix issues in SPARTA docs
  doc/Section_commands.txt
  doc/Section_howto.html
  doc/Section_howto.txt
  doc/compute_property_grid.html
  doc/compute_property_grid.txt
  doc/dump_modify.html
  doc/dump_modify.txt
  doc/fix.html
  doc/fix.txt
  doc/fix_ave_surf.html
  doc/fix_ave_surf.txt
  doc/fix_ave_time.html
  doc/fix_ave_time.txt
  doc/jump.html
  doc/jump.txt
  doc/variable.txt
Labels: documentation

#152 Fix issue in restart file read
  src/read_restart.cpp
  src/update.cpp
  src/update.h
Labels: bugfix
