Repository sparta/sparta, pull requests merged in 2020-06, with the labels that each got.

#161 Fix issues in low-memory restart file read/write
  src/particle.cpp
  src/particle.h
  src/pointers.h
  src/read_restart.cpp
  src/write_restart.cpp
Labels: bugfix

#155 Initial cmake build system
  BUILD_CMAKE.md
  cmake/CMakeLists.txt
  cmake/Modules/FindFFTW2.cmake
  cmake/Modules/FindFFTW3.cmake
  cmake/Modules/FindMKL.cmake
  cmake/check_for_sparta_build_artifacts.sh
  cmake/common/print/sparta_options.cmake
  cmake/common/process/sparta_build_options.cmake
  cmake/common/set/kokkos_cmake_defaults.cmake
  cmake/common/set/kokkos_cuda_cmake_defaults.cmake
  cmake/common/set/sparta_cmake_defaults.cmake
  cmake/common/set/sparta_options.cmake
  cmake/presets/astra_kokkos.cmake
  cmake/presets/chama.cmake
  cmake/presets/chama_big.cmake
  cmake/presets/chama_mpich.cmake
  cmake/presets/kokkos_common.cmake
  cmake/presets/kokkos_cuda.cmake
  cmake/presets/kokkos_mpi_only.cmake
  cmake/presets/kokkos_omp.cmake
  cmake/presets/kokkos_phi.cmake
  cmake/presets/mac.cmake
  cmake/presets/mac_mpi.cmake
  cmake/presets/mpi.cmake
  cmake/presets/mpi_big.cmake
  cmake/presets/mpi_debug.cmake
  cmake/presets/openmpi.cmake
  cmake/presets/serial.cmake
  cmake/presets/serial_debug.cmake
  doc/Section_accelerate.txt
  doc/Section_packages.txt
  doc/Section_python.txt
  doc/Section_start.txt
  doc/accelerate_kokkos.txt
  lib/kokkos/Makefile.kokkos
  src/CMakeLists.txt
  src/FFT/CMakeLists.txt
  src/KOKKOS/CMakeLists.txt
  src/Makefile
  src/Purge.list
  src/STUBS/CMakeLists.txt
  src/image.cpp
Labels: enhancement

#166 Remove duplicated text in fix_balance doc page
  doc/fix_balance.txt
Labels: documentation, enhancement
