Repository sparta/sparta, pull requests merged in 2021-06, with the labels that each got.

#261 Fix typo in accelerate_kokkos doc page
  doc/accelerate_kokkos.html
  doc/accelerate_kokkos.txt
Labels: documentation

#258 Fix typo in create_grid docs
  doc/create_grid.html
  doc/create_grid.txt
Labels: documentation

#259 Fix typos in compute_distsurf_grid doc page
  doc/compute_distsurf_grid.html
  doc/compute_distsurf_grid.txt
Labels: documentation

#257 Fix bug in grid_surf when collide isn't initialized
  src/collide.h
  src/grid_surf.cpp
Labels: bugfix

#267 Fixed incompatibility between Python 2 and 3 in grid2paraview.py
  tools/paraview/grid2paraview.py
  tools/paraview/grid2paraview_unit_test.py
  tools/paraview/tests/input_files/circle_grid.txt
Labels: bugfix, paraview

#262 Fix bugs in surf_collide methods
  src/KOKKOS/create_particles_kokkos.cpp
  src/KOKKOS/fix_emit_face_kokkos.cpp
  src/KOKKOS/fix_vibmode_kokkos.cpp
  src/KOKKOS/fix_vibmode_kokkos.h
  src/KOKKOS/modify_kokkos.cpp
  src/KOKKOS/modify_kokkos.h
  src/KOKKOS/surf_collide_diffuse_kokkos.cpp
  src/KOKKOS/surf_collide_diffuse_kokkos.h
  src/create_particles.cpp
  src/fix.cpp
  src/fix.h
  src/fix_ambipolar.cpp
  src/fix_ambipolar.h
  src/fix_emit_face.cpp
  src/fix_emit_face_file.cpp
  src/fix_emit_surf.cpp
  src/fix_vibmode.cpp
  src/fix_vibmode.h
  src/modify.cpp
  src/modify.h
  src/particle.cpp
  src/surf_collide_cll.cpp
  src/surf_collide_diffuse.cpp
  src/surf_collide_impulsive.cpp
  src/surf_collide_td.cpp
Labels: bugfix, physics issue

#268 Rotrel equilibrium fix
  cmake/common/set/sparta_cmake_defaults.cmake
  doc/collide.html
  doc/collide.txt
  examples/relax_const/in.relax_const
  examples/relax_const/n2.species
  examples/relax_const/n2.vss
  examples/relax_variable/in.relax_variable
  examples/relax_variable/n2.species
  examples/relax_variable/n2.vss
  src/KOKKOS/collide_vss_kokkos.cpp
  src/collide_vss.cpp
Labels: bugfix

#270 Fix indexing bug in Kokkos surf tally
  src/KOKKOS/compute_surf_kokkos.cpp
Labels: KOKKOS package, bugfix
