Repository sparta/sparta, pull requests merged in 2021-02, with the labels that each got.

#226 Prevent hang when using global mem/limit
  src/grid.cpp
Labels: bugfix

#206 Fix mflux
  src/KOKKOS/compute_boundary_kokkos.h
  src/KOKKOS/compute_surf_kokkos.h
  src/compute_boundary.cpp
  src/compute_isurf_grid.cpp
  src/compute_surf.cpp
Labels: bugfix

#211 grid: do not include axial cell size in radial weight computation
  examples/axi/in.axi
  examples/axi/log.17Feb21.mpi_1.axi
  examples/axi/log.17Feb21.mpi_4.axi
  examples/axi/log.24Aug20.mpi_4.axi
  src/grid.cpp
Labels: bugfix

#234 Fix bug in surf grow() call
  src/grid_surf.cpp
Labels: bugfix

#232 Fix issue in Kokkos compute surf
  src/KOKKOS/compute_surf_kokkos.cpp
  src/KOKKOS/compute_surf_kokkos.h
Labels: KOKKOS package, bugfix

#235 Change reaction tally to bigint to prevent overflow
  src/KOKKOS/kokkos_type.h
  src/KOKKOS/react_bird_kokkos.cpp
  src/KOKKOS/react_bird_kokkos.h
  src/react_bird.cpp
  src/react_bird.h
Labels: enhancement

#236 Preserve previous axisymmetric weighting scheme as an option
  doc/Section_packages.html
  doc/accelerate_kokkos.html
  doc/global.html
  doc/global.txt
  examples/axi/in.axi
  examples/axi/log.17Feb21.mpi_4.axi
  examples/axi/log.24Aug20.mpi_1.axi
  examples/axi/log.24Aug20.mpi_4.axi
  src/KOKKOS/grid_kokkos.cpp
  src/grid.cpp
Labels: enhancement
