Repository sparta/sparta, pull requests merged in 2023-06, with the labels that each got.

#416 Incident flux
  doc/compute_surf.html
  doc/compute_surf.txt
  src/compute_surf.cpp
Labels: enhancement

#415 Fix logic bug in surf removal code
  examples/surf/log.02Jun23.mpi_1.surf.remove
  examples/surf/log.02Jun23.mpi_4.surf.remove
  src/remove_surf.cpp
Labels: bugfix

#409 Add variable Np support to the fix emit/surf command
  doc/fix_emit_surf.html
  doc/fix_emit_surf.txt
  src/create_particles.cpp
  src/cut2d.h
  src/cut3d.h
  src/fix_ablate.cpp
  src/fix_emit_surf.cpp
  src/fix_emit_surf.h
  src/fix_grid_check.cpp
  src/grid.cpp
  src/grid_surf.cpp
Labels: enhancement

#417 Correct warning for tvib grid and fix vibmode
  src/compute_grid.cpp
  src/compute_grid.h
Labels: bugfix

#419 Fix random and proc style balance_grid input parse
  src/balance_grid.cpp
Labels: bugfix

#420 Port changes from #416 to Kokkos, fixes numerical regressions
  src/KOKKOS/compute_surf_kokkos.h
Labels: bugfix

#421 Normfactor computation consistent with surfaces for axisymm case
  src/compute_boundary.cpp
Labels: bugfix

#422 grid dimensions parsing fix
  tools/paraview/grid2paraview.py
Labels: bugfix

#423 Add Kokkos SYCL Makefile
  src/MAKE/Makefile.kokkos_sycl
Labels: enhancement, KOKKOS package
