Repository sparta/sparta, pull requests merged in 2024-07, with the labels that each got.

#491 Add custom per-surf options to fix emit/surf
  doc/fix_emit_surf.html
  doc/fix_emit_surf.txt
  doc/read_surf.html
  doc/read_surf.txt
  src/balance_grid.cpp
  src/create_isurf.cpp
  src/dump_surf.cpp
  src/fix_balance.cpp
  src/fix_emit_surf.cpp
  src/fix_emit_surf.h
  src/geometry.cpp
  src/grid.cpp
  src/grid_surf.cpp
Labels: enhancement

#488 Update doc page and error checking for custom command
  doc/custom.html
  doc/custom.txt
  doc/fix_emit_surf.html
  doc/fix_emit_surf.txt
  examples/custom/README
  src/custom.cpp
Labels: documentation

#284 Add mars/venus data
  data/co2.species.vib
  data/mars.species
  data/mars.tce
  data/mars.vss
  examples/vibrate/co2.species
  examples/vibrate/co2.species.vib
  examples/vibrate/log.12Jul24.mpi_1.vibrate
  examples/vibrate/log.12Jul24.mpi_4.vibrate
Labels: enhancement

#499 Fix for issue #464 (write_surf flag and surf2paraview)
  tools/paraview/CMakeLists.txt
  tools/paraview/surf2paraview.py
  tools/paraview/surf2paraview_unit_test.py
  tools/paraview/test_data/data.circle_w_type
  tools/paraview/test_data/data.sphere_w_type
Labels: enhancement, paraview
