Repository sparta/sparta, pull requests merged in 2024-10, with the labels that each got.

#526 Update surf2paraview.py
  tools/paraview/surf2paraview.py
Labels: bugfix, paraview

#524 Add fix halt, copied and adapted from LAMMPS
  doc/fix_halt.html
  doc/fix_halt.txt
  doc/run.html
  doc/run.txt
  src/fix.cpp
  src/fix.h
  src/fix_halt.cpp
  src/fix_halt.h
  src/modify.cpp
  src/modify.h
  src/timer.cpp
  src/timer.h
  src/update.cpp
  src/utils.cpp
  src/utils.h
Labels: enhancement, ready_for_merge

#528 Work around roundoff issues in axisymmetric code
  src/KOKKOS/geometry_kokkos.h
  src/geometry.cpp
Labels: bugfix, ready_for_merge

#530 Renumber implicit surfaces in `write_surf` since ablation may remove surfs
  doc/write_surf.html
  doc/write_surf.txt
  src/write_surf.cpp
  src/write_surf.h
Labels: bugfix

#531 Two bugfixes
  src/dump_image.cpp
  src/write_surf.cpp
  src/write_surf.h
Labels: bugfix, ready_for_merge

#532 Document more clearly a round-off with axisymmetric gas/surface collisions
  src/KOKKOS/geometry_kokkos.h
  src/geometry.cpp
Labels: enhancement
