Repository sparta/sparta, pull requests merged in 2024-09, with the labels that each got.

#502 Surf emit momentum
  doc/compute_surf.html
  doc/compute_surf.txt
  examples/emit/in.emit.surf.normal
  src/KOKKOS/compute_surf_kokkos.h
  src/compute_surf.cpp
  src/fix_emit_surf.cpp
  src/update.h
Labels: enhancement, ready_for_merge

#515 Update SPARTA version for next release
  doc/Manual.html
  doc/Manual.txt
  src/version.h
Labels: maintenance

#518 Update Kokkos library in SPARTA to v4.4.1
  cmake/common/set/kokkos_cuda_cmake_defaults.cmake
  cmake/common/set/style_file_glob.cmake
  lib/kokkos/CHANGELOG.md
  lib/kokkos/CMakeLists.txt
  lib/kokkos/Makefile.kokkos
  lib/kokkos/cmake/KokkosCore_config.h.in
  lib/kokkos/cmake/kokkos_enable_options.cmake
  lib/kokkos/containers/unit_tests/TestWithoutInitializing.hpp
  lib/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp
  lib/kokkos/core/src/Cuda/Kokkos_CudaSpace.hpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_Instance.cpp
  lib/kokkos/core/src/Kokkos_View.hpp
  lib/kokkos/core/src/OpenMP/Kokkos_OpenMP.cpp
  lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_Instance.hpp
  lib/kokkos/core/src/OpenMP/Kokkos_OpenMP_UniqueToken.hpp
  lib/kokkos/core/src/View/Kokkos_ViewAlloc.hpp
  lib/kokkos/core/src/impl/Kokkos_ViewCtor.hpp
  lib/kokkos/core/src/impl/Kokkos_ViewMapping.hpp
  lib/kokkos/core/unit_test/TestViewOfViews.hpp
  lib/kokkos/core/unit_test/cuda/TestCuda_Spaces.cpp
  lib/kokkos/master_history.txt
  lib/kokkos/simd/src/Kokkos_SIMD_AVX2.hpp
  lib/kokkos/simd/unit_tests/TestSIMD.cpp
  lib/kokkos/simd/unit_tests/include/TestSIMD_Construction.hpp
  src/KOKKOS/CMakeLists.txt
  src/KOKKOS/collide_vss_kokkos.cpp
  src/KOKKOS/comm_kokkos.cpp
  src/KOKKOS/compute_boundary_kokkos.cpp
  src/KOKKOS/compute_count_kokkos.cpp
  src/KOKKOS/compute_eflux_grid_kokkos.cpp
  src/KOKKOS/compute_grid_kokkos.cpp
  src/KOKKOS/compute_pflux_grid_kokkos.cpp
  src/KOKKOS/compute_sonine_grid_kokkos.cpp
  src/KOKKOS/compute_surf_kokkos.cpp
  src/KOKKOS/compute_thermal_grid_kokkos.cpp
  src/KOKKOS/compute_tvib_grid_kokkos.cpp
  src/KOKKOS/fix_temp_rescale_kokkos.cpp
  src/KOKKOS/grid_custom_kokkos.cpp
  src/KOKKOS/grid_kokkos.cpp
  src/KOKKOS/grid_kokkos.h
  src/KOKKOS/kokkos_type.h
  src/KOKKOS/particle_custom_kokkos.cpp
  src/KOKKOS/particle_kokkos.cpp
  src/KOKKOS/particle_kokkos.h
  src/KOKKOS/react_bird_kokkos.cpp
  src/KOKKOS/react_bird_kokkos.h
  src/KOKKOS/surf_collide_diffuse_kokkos.cpp
  src/KOKKOS/surf_custom_kokkos.cpp
  src/KOKKOS/surf_kokkos.cpp
  src/KOKKOS/surf_kokkos.h
  src/KOKKOS/update_kokkos.cpp
Labels: KOKKOS package, bugfix, maintenance
