Repository sparta/sparta, pull requests merged in 2024-08, with the labels that each got.

#501 Fix typo in error message in surf_react_adsorb.cpp
  src/surf_react_adsorb.cpp
Labels: documentation

#463 Modified small corner value removal in fix_ablate
  doc/Section_commands.html
  doc/Section_commands.txt
  doc/fix_ablate.html
  doc/fix_ablate.txt
  doc/fix_ave_histo.html
  doc/fix_ave_histo.txt
  doc/fix_ave_time.html
  doc/fix_ave_time.txt
  doc/read_isurf.html
  doc/read_isurf.txt
  examples/ablation/in.ablation.2d
  examples/explicit2implicit/in.exp2imp.sphere.3d
  examples/explicit2implicit/log.23Apr24.mpi_1.exp2imp.circle.2d
  examples/explicit2implicit/log.23Apr24.mpi_1.exp2imp.sphere.3d
  examples/explicit2implicit/log.23Apr24.mpi_4.exp2imp.circle.2d
  examples/explicit2implicit/log.23Apr24.mpi_4.exp2imp.sphere.3d
  src/create_isurf.cpp
  src/fix_ablate.cpp
  src/fix_ablate.h
Labels: enhancement, ready_for_merge

#466 Added requirement for cpp11
  cmake/CMakeLists.txt
  cmake/common/process/sparta_build_options.cmake
  doc/Section_start.html
  doc/Section_start.txt
  src/MAKE/Makefile.bgq
  src/MAKE/Makefile.bgq_big
  src/MAKE/Makefile.bgq_xlr
  src/MAKE/Makefile.chama
  src/MAKE/Makefile.chama_big
  src/MAKE/Makefile.chama_mpich
  src/MAKE/Makefile.mac
  src/MAKE/Makefile.mac_mpi
  src/MAKE/Makefile.mpi
  src/MAKE/Makefile.mpi_big
  src/MAKE/Makefile.mpi_debug
  src/MAKE/Makefile.openmpi
  src/MAKE/Makefile.png
  src/MAKE/Makefile.redsky
  src/MAKE/Makefile.redsky_mpich
  src/MAKE/Makefile.serial
  src/MAKE/Makefile.serial_debug
  src/MAKE/Makefile.wsv
  src/math_eigen.cpp
  src/math_eigen.h
  src/math_eigen_impl.h
  src/spatype.h
Labels: maintenance

#505 Fix bugs in surf_react_adsorb
  src/surf_react_adsorb.cpp
  src/surf_react_adsorb.h
Labels: bugfix

#510 Prepare SPARTA Kokkos for AMD MI300A APUs
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/update_kokkos.cpp
  src/MAKE/Makefile.elcapitan_kokkos
Labels: enhancement, KOKKOS package

#508 Fix reread surf custom dat
  examples/custom/data.cube.custom.2
  examples/custom/in.custom.cube.reread
  examples/custom/log.28Aug24.mpi_1.custom.cube.reread
  examples/custom/log.28Aug24.mpi_4.custom.cube.reread
  src/read_surf.cpp
Labels: bugfix

#513 Fix bug with ambipolar when particle struct is realloc'd
  src/KOKKOS/collide_vss_kokkos.cpp
  src/collide_vss.cpp
Labels: bugfix, ready_for_merge
