Repository sparta/sparta, pull requests merged in 2024-03, with the labels that each got.

#458 Fix small issues in SPARTA
  cmake/common/process/sparta_build_options.cmake
  doc/group.txt
Labels: documentation, build system

#459 Update version in SPARTA for 7Mar2024 patch
  doc/Manual.html
  doc/Manual.txt
  doc/Section_packages.html
  doc/Section_start.html
  doc/dump.html
  doc/fix_ave_grid.html
  doc/group.html
  src/version.h
Labels: maintenance

#447 Added functionality to convert explicit surfaces to implicit surfaces…
  cmake/common/set/sparta_cmake_defaults.cmake
  doc/JPG/implicit_bend.png
  doc/JPG/implicit_bend_small.png
  doc/JPG/implicit_bend_uneven.png
  doc/JPG/implicit_bend_uneven_small.png
  doc/JPG/implicit_circle.png
  doc/JPG/implicit_circle_small.png
  doc/JPG/implicit_cone.png
  doc/JPG/implicit_cone_small.png
  doc/JPG/implicit_corner.png
  doc/JPG/implicit_corner_small.png
  doc/JPG/implicit_eggcarton.png
  doc/JPG/implicit_eggcarton_small.png
  doc/JPG/implicit_pointy.png
  doc/JPG/implicit_pointy_small.png
  doc/create_isurf.html
  doc/create_isurf.txt
  doc/read_isurf.html
  doc/read_isurf.txt
  examples/explicit2implicit/README
  examples/explicit2implicit/air.species
  examples/explicit2implicit/air.vss
  examples/explicit2implicit/data.circle2d
  examples/explicit2implicit/data.sphere3d
  examples/explicit2implicit/in.exp2imp.circle.2d
  examples/explicit2implicit/in.exp2imp.sphere.3d
  examples/explicit2implicit/log.11Mar24.mpi_1.exp2imp.circle.2d
  examples/explicit2implicit/log.11Mar24.mpi_1.exp2imp.sphere.3d
  examples/explicit2implicit/log.11Mar24.mpi_4.exp2imp.circle.2d
  examples/explicit2implicit/log.11Mar24.mpi_4.exp2imp.sphere.3d
  src/create_isurf.cpp
  src/create_isurf.h
  src/grid.cpp
  src/read_isurf.cpp
  src/surf.cpp
Labels: enhancement
